# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.platformapiserver.name }}-payload-volume-claim
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.platformapiserver.name }}-payload-volume-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.platformapiserver.payloadService.capacity }}
