# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.platformapiserver.name}}-cluster-role
rules: 
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - persistentvolumes
  - persistentvolumeclaims
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete  
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
- apiGroups:
  - clara.nvidia.com
  resources:
  - pipelines
  - pipelinejobs
  - payloads
  - pipelineservices  
  verbs:
  - get
  - list
  - watch
  - update
  - delete
  - create
  - patch
