apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fluentd-ds.fullname" . }}
  labels:
    k8s-app: {{ template "fluentd-ds.fullname" . }}
    version: v1
    app: {{ template "fluentd-ds.name" . }}
    chart: {{ template "fluentd-ds.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "fluentd-ds.name" . }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fluentd-ds.name" . }}
        release: {{ .Release.Name }}
        k8s-app: {{ template "fluentd-ds.fullname" . }}
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      imagePullSecrets:
      - name: {{ .Values.image.secret }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: FLUENTD_ARGS
          value: -c /etc/fluentd-config/fluentd.conf
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluentd-config
        - name: pos-volume
          mountPath: /tmp/
      # Needed to access pod details
      serviceAccountName: {{ template "fluentd-ds.fullname" . }}-fluentd
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers # Mount /var/lib/docker to be able to read symlink logs.
        hostPath:
          path: /var/lib/docker/containers
      - name: pos-volume    # Mount the pos files to host so that tail pointer is not lost on fluentd restarts.
        hostPath:
          path: /var/log/fluentd-pos
      - name: config-volume
        configMap:
          name: {{ template "fluentd-ds.fullname" . }}-logging-config
