apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fluentd-ds.fullname" . }}-fluentd
  labels:
    app: {{ template "fluentd-ds.name" . }}
    chart: {{ template "fluentd-ds.chart" . }}
    release: {{ .Release.Name }}