apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deepstream-4-egx.fullname" . }}
  labels:
{{ include "deepstream-4-egx.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deepstream-4-egx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deepstream-4-egx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-0"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [{{ .Values.command.appname}}]
          args: ["-c", {{ .Values.command.appcfg0}}, "-p", "0"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: vodmount
              mountPath: /root/vod20
        - name: "{{ .Chart.Name }}-1"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [{{ .Values.command.appname}}]
          args: ["-c", {{ .Values.command.appcfg1}}, "-p", "0"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: vodmount
              mountPath: /root/vod20	      
      volumes:
        - name: vodmount
          hostPath:
            path: /home/ubuntu/deepstream/vod_20	    
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
