# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clara-renderer.fullname" . }}
  labels:
{{ include "clara-renderer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clara-renderer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "clara-renderer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: ui-{{ .Chart.Name }}
        image: "{{ .Values.images.namespace }}/{{ .Values.images.renderui }}:{{ .Values.images.tag }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
        - name: SERVICE_RSDS_IP
          value: "localhost"
        - name: SERVICE_RSDS_PORT
          value: "50055"
        - name: SERVICE_RSNG_IP
          value: "localhost"
        - name: SERVICE_RSNG_PORT
          value: "2050"
        - name: NODE_ENV
          value: "production"
        ports:
          - name: ui
            containerPort: 8080
            hostPort: 8080
            protocol: TCP
      - name: renderer-{{ .Chart.Name }}
        image: "{{ .Values.images.namespace }}/{{ .Values.images.renderserver }}:{{ .Values.images.tag }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
          - name: renderer
            containerPort: 2050
            protocol: TCP
      - name: dataset-service-{{ .Chart.Name }}
        image: "{{ .Values.images.namespace }}/{{ .Values.images.datasetservice }}:{{ .Values.images.tag }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
        - name: DATASET_REPO_PATH
          value: "/datasets"
        - name: SERVICE_RSDS_PORT
          value: "50055"
        - name: ENABLE_DATASET_LISTENER
          value: "{{ .Values.rsds.enableDatasetListener }}"
        - name: RSDS_AGENT_NAME
          value: "{{ .Values.rsds.agentName }}"
        - name: RSDS_PULL_INTERVAL
          value: "{{ .Values.rsds.pullInterval }}"
        - name: RSDS_RETRY_LIMIT
          value: "{{ .Values.rsds.retryLimit }}"
        - name: SERVICE_RSNG_IP
          value: "localhost"
        - name: SERVICE_RSNG_PORT
          value: "2050"
        - name: SERVICE_RSUI_IP
          value: "localhost"
        - name: SERVICE_RSUI_PORT
          value: "8080"
        - name: PYTHONPATH
          value: "/app"
        ports:
          - name: dataset-service
            containerPort: 50055
            protocol: TCP
        volumeMounts:
        - name: render-service-volume
          mountPath: "/datasets"
      volumes:
      - name: render-service-volume
        persistentVolumeClaim:
          claimName: render-service