# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

# Default values for results-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  namespace: clara
  pullPolicy: IfNotPresent
  pullSecrets: []
  resultsService: resultsservice
  tag: latest

resultsService:
  serviceType: ClusterIP
